# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build Directus with extensions

on:
  push:
    branches:
      - main
    paths:
      - apps/portal/**
      - packages/directus-extensions/**
      - .github/workflows/main_cms-directus.yml
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - apps/pbswebsite/**
      - packages/nuxtui/**
      - .github/workflows/main_cms-directus.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://potsdamerbuergerstiftung.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fcc6df26286044aca3025880c3e04858 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e852bbbc0ae44e77a5dc1ee5121bb399 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: potsdamerbuergerstiftung.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fcc6df26286044aca3025880c3e04858 }}/potsdamerbuergerstiftung/portal:${{ github.sha }}
        file: ./apps/portal/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cms-directus'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ed7e36dfab4d490aa3482375ac5f1b75 }}
        images: 'potsdamerbuergerstiftung.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fcc6df26286044aca3025880c3e04858 }}/potsdamerbuergerstiftung/portal:${{ github.sha }}'
